x-common-variables: &common-variables
  VITE_HOST: '0.0.0.0'
  VITE_PORT: '${VITE_PORT:-5173}'
  VITE_HMR_HOST: '${VITE_HMR_HOST:-localhost}'
  XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
  XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'

services:
  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspaces:cached
    environment:
      <<: *common-variables
  app:
    build:
      context: './services/app'
      dockerfile: ../../operations/services/app/Dockerfile
      target: base
      args:
        WWWGROUP: '${WWWGROUP}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8080}:8080'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      <<: *common-variables
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    env_file: './services/app/.env'
    # volumes:
    #   - './services/app:/var/www/html'
    #   - './services/app/database/database.sqlite:/var/www/html/database/database.sqlite'
    networks:
      - coolify
    depends_on:
      - redis
      - mailpit
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'gs-redis:/data'
    # networks:
    #   - gs
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    # networks:
    #   - gs
# networks:
#   gs:
#     driver: bridge
networks:
  coolify:
    external: true
volumes:
  gs-redis:
    driver: local
